from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
from database_function import *

from PyQt5.uic import loadUiType

ui,_=loadUiType('untitled.ui')

class MainApp(QMainWindow,ui):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)
        self.logged_in=False
        self.logged_in_user=None
        self.logged_in_password=None
        self.Handle_Ui_Changes()
        self.handle_drop()
        self.Handle_Buttons()
        

    def Handle_Buttons(self):
        self.pushButton_5.clicked.connect(self.Show_Themes)
        self.pushButton_8.clicked.connect(self.Hide_Themes)
        self.pushButton_4.clicked.connect(self.Open_Hod)
        self.pushButton.clicked.connect(self.Open_Teacher_Schedule)
        self.pushButton_2.clicked.connect(self.Open_Class_Schedule)
        self.pushButton_3.clicked.connect(self.Open_Free_Teacher)
        self.pushButton_11.clicked.connect(self.add_admin)
        self.pushButton_9.clicked.connect(self.login)
        self.pushButton_13.clicked.connect(self.logout)
        self.pushButton_14.clicked.connect(self.Open_Hod)
        self.pushButton_12.clicked.connect(self.remove_admin)
        self.pushButton_15.clicked.connect(self.open_pass_change)
        self.pushButton_16.clicked.connect(self.pass_change)
        self.pushButton_17.clicked.connect(self.add_teacher)
        self.pushButton_18.clicked.connect(self.remove_teacher)
        self.pushButton_20.clicked.connect(self.add_subject)
        self.pushButton_21.clicked.connect(self.remove_subject)
        self.pushButton_19.clicked.connect(self.add_time_tabe)
        

    def Handle_Ui_Changes(self):
        self.Hide_Themes()
        self.tabWidget.tabBar().setVisible(False)
        self.hide_logout()

    def handle_drop(self):
        admin_list=get_admin_db()
        teacher_list=get_teacher_db()
        subject_list=get_subject_db()
        teacher_list.insert(0,"Null")
        subject_list.insert(0,"Null")
        self.comboBox_4.clear()
        self.comboBox_5.clear()
        self.comboBox_6.clear()
        self.comboBox_7.clear()
        self.comboBox_8.clear()
        self.comboBox_9.clear()
        self.comboBox_10.clear()
        self.comboBox_11.clear()
        self.comboBox_12.clear()
        self.comboBox_13.clear()
        self.comboBox_14.clear()
        self.comboBox_15.clear()
        self.comboBox_16.clear()
        self.comboBox_17.clear()
        self.comboBox_18.clear()
        self.comboBox_19.clear()
        self.comboBox_20.clear()
        self.comboBox_21.clear()
        self.comboBox_22.clear()
        self.comboBox_23.clear()
        self.comboBox_24.clear()
        self.comboBox_25.clear()
        self.comboBox_26.clear()
        self.comboBox_27.clear()
        self.comboBox_28.clear()
        self.comboBox_29.clear()
        self.comboBox_30.clear()
        self.comboBox_31.clear()
        self.comboBox_32.clear()
        self.comboBox_33.clear()
        self.comboBox_34.clear()
        self.comboBox_35.clear()
        self.comboBox_36.clear()
        self.comboBox_37.clear()
        self.comboBox_38.clear()
        self.comboBox_39.clear()
        self.comboBox_40.clear()
        self.comboBox_41.clear()
        self.comboBox_42.clear()
        self.comboBox_43.clear()
        self.comboBox_44.clear()
        self.comboBox_45.clear()
        self.comboBox_46.clear()
        self.comboBox_47.clear()
        self.comboBox_48.clear()
        self.comboBox_49.clear()
        self.comboBox_50.clear()
        self.comboBox_51.clear()
        self.comboBox_52.clear()
        self.comboBox_53.clear()
        self.comboBox_54.clear()
        self.comboBox_55.clear()
        self.comboBox_56.clear()
        self.comboBox_57.clear()
        self.comboBox_58.clear()
        self.comboBox_59.clear()
        self.comboBox_60.clear()
        self.comboBox_61.clear()
        self.comboBox_62.clear()
        self.comboBox_63.clear()
        self.comboBox_64.clear()
        self.comboBox_65.clear()
        self.comboBox_66.clear()
        self.comboBox_67.clear()
        self.comboBox_68.clear()
        self.comboBox_69.clear()
        self.comboBox_70.clear()
        self.comboBox_71.clear()
        self.comboBox_72.clear()
        self.comboBox_73.clear()
        self.comboBox_74.clear()
        self.comboBox_75.clear()
        self.comboBox_76.clear()
        self.comboBox_77.clear()
        self.comboBox_78.clear()
        self.comboBox_79.clear()
        self.comboBox_80.clear()
        self.comboBox_81.clear()
        self.comboBox_82.clear()
        self.comboBox_83.clear()
        self.comboBox_84.clear()
        self.comboBox_85.clear()
        self.comboBox_86.clear()
        self.comboBox_87.clear()
        self.comboBox_88.clear()
        self.comboBox_89.clear()
        self.comboBox_90.clear()
        self.comboBox_91.clear()
        self.comboBox_92.clear()
        self.comboBox_93.clear()
        self.comboBox_94.clear()
        self.comboBox_95.clear()
        self.comboBox_96.clear()
        self.comboBox_97.clear()
        self.comboBox_98.clear()
        self.comboBox_99.clear()
        self.comboBox_100.clear()
        self.comboBox_101.clear()
        self.comboBox_102.clear()
        self.comboBox_103.clear()
        self.comboBox_104.clear()
        self.comboBox_105.clear()
        self.comboBox_106.clear()
        self.comboBox_107.clear()
        self.comboBox_108.clear()
        self.comboBox_109.clear()
        self.comboBox_110.clear()
        self.comboBox_111.clear()
        self.comboBox_112.clear()
        self.comboBox_113.clear()
        self.comboBox_114.clear()
        self.comboBox_115.clear()
        self.comboBox_116.clear()
        self.comboBox_117.clear()
        self.comboBox_118.clear()
        self.comboBox_119.clear()
        self.comboBox_120.clear()
        self.comboBox_121.clear()
        self.comboBox_122.clear()
        self.comboBox_123.clear()
        self.comboBox_124.clear()
        self.comboBox_125.clear()
        self.comboBox_126.clear()
        self.comboBox_127.clear()
        self.comboBox_128.clear()
        self.comboBox_129.clear()
        self.comboBox_130.clear()
        self.comboBox_131.clear()
        self.comboBox_132.clear()
        self.comboBox_133.clear()
        self.comboBox_134.clear()
        self.comboBox_135.clear()
        self.comboBox_136.clear()
        self.comboBox_137.clear()
        self.comboBox_138.clear()
        self.comboBox_139.clear()
        self.comboBox_140.clear()
        self.comboBox_141.clear()
        self.comboBox_142.clear()
        self.comboBox_143.clear()
        self.comboBox_144.clear()
        self.comboBox_145.clear()
        self.comboBox_146.clear()
        self.comboBox_147.clear()
        self.comboBox_148.clear()
        self.comboBox_149.clear()
        self.comboBox_150.clear()
        self.comboBox_151.clear()
        self.comboBox_152.clear()
        self.comboBox_153.clear()
        self.comboBox_154.clear()
        self.comboBox_155.clear()
        self.comboBox_156.clear()
        self.comboBox_157.clear()
        self.comboBox_158.clear()
        self.comboBox_159.clear()
        self.comboBox_160.clear()
        self.comboBox_161.clear()
        self.comboBox_162.clear()
        self.comboBox_163.clear()
        self.comboBox_164.clear()
        self.comboBox_165.clear()
        self.comboBox_166.clear()
        self.comboBox_167.clear()
        self.comboBox_168.clear()
        self.comboBox_169.clear()
        self.comboBox_170.clear()
        self.comboBox_171.clear()
        self.comboBox_172.clear()
        self.comboBox_173.clear()
        self.comboBox_174.clear()
        self.comboBox_175.clear()

        self.comboBox_176.clear()


        self.comboBox_4.addItems(admin_list)
        self.comboBox_5.addItems(['Asst.Prof.','HOD','OSD','Principal'])
        self.comboBox_6.addItems(["CSE"])
        self.comboBox_7.addItems(teacher_list)

        #Subjects in schedule tab
        
        self.comboBox_8.addItems(subject_list)
        self.comboBox_9.addItems(subject_list)
        self.comboBox_10.addItems(subject_list)
        self.comboBox_11.addItems(subject_list)
        self.comboBox_12.addItems(subject_list)
        self.comboBox_13.addItems(subject_list)
        self.comboBox_14.addItems(subject_list)
        self.comboBox_22.addItems(subject_list)
        self.comboBox_23.addItems(subject_list)
        self.comboBox_24.addItems(subject_list)
        self.comboBox_25.addItems(subject_list)
        self.comboBox_26.addItems(subject_list)
        self.comboBox_27.addItems(subject_list)
        self.comboBox_28.addItems(subject_list)
        self.comboBox_36.addItems(subject_list)
        self.comboBox_37.addItems(subject_list)
        self.comboBox_38.addItems(subject_list)
        self.comboBox_39.addItems(subject_list)
        self.comboBox_40.addItems(subject_list)
        self.comboBox_41.addItems(subject_list)
        self.comboBox_42.addItems(subject_list)
        self.comboBox_50.addItems(subject_list)
        self.comboBox_51.addItems(subject_list)
        self.comboBox_52.addItems(subject_list)
        self.comboBox_53.addItems(subject_list)
        self.comboBox_54.addItems(subject_list)
        self.comboBox_55.addItems(subject_list)
        self.comboBox_56.addItems(subject_list)
        self.comboBox_64.addItems(subject_list)
        self.comboBox_65.addItems(subject_list)
        self.comboBox_66.addItems(subject_list)
        self.comboBox_67.addItems(subject_list)
        self.comboBox_68.addItems(subject_list)
        self.comboBox_69.addItems(subject_list)
        self.comboBox_70.addItems(subject_list)
        self.comboBox_78.addItems(subject_list)
        self.comboBox_79.addItems(subject_list)
        self.comboBox_80.addItems(subject_list)
        self.comboBox_81.addItems(subject_list)
        self.comboBox_82.addItems(subject_list)
        self.comboBox_83.addItems(subject_list)
        self.comboBox_84.addItems(subject_list)
        self.comboBox_92.addItems(subject_list)
        self.comboBox_93.addItems(subject_list)
        self.comboBox_94.addItems(subject_list)
        self.comboBox_95.addItems(subject_list)
        self.comboBox_96.addItems(subject_list)
        self.comboBox_97.addItems(subject_list)
        self.comboBox_98.addItems(subject_list)
        self.comboBox_106.addItems(subject_list)
        self.comboBox_107.addItems(subject_list)
        self.comboBox_108.addItems(subject_list)
        self.comboBox_109.addItems(subject_list)
        self.comboBox_110.addItems(subject_list)
        self.comboBox_111.addItems(subject_list)
        self.comboBox_112.addItems(subject_list)
        self.comboBox_120.addItems(subject_list)
        self.comboBox_121.addItems(subject_list)
        self.comboBox_122.addItems(subject_list)
        self.comboBox_123.addItems(subject_list)
        self.comboBox_124.addItems(subject_list)
        self.comboBox_125.addItems(subject_list)
        self.comboBox_126.addItems(subject_list)
        self.comboBox_134.addItems(subject_list)
        self.comboBox_135.addItems(subject_list)
        self.comboBox_136.addItems(subject_list)
        self.comboBox_137.addItems(subject_list)
        self.comboBox_138.addItems(subject_list)
        self.comboBox_139.addItems(subject_list)
        self.comboBox_140.addItems(subject_list)
        self.comboBox_148.addItems(subject_list)
        self.comboBox_149.addItems(subject_list)
        self.comboBox_150.addItems(subject_list)
        self.comboBox_151.addItems(subject_list)
        self.comboBox_152.addItems(subject_list)
        self.comboBox_153.addItems(subject_list)
        self.comboBox_154.addItems(subject_list)
        self.comboBox_162.addItems(subject_list)
        self.comboBox_163.addItems(subject_list)
        self.comboBox_164.addItems(subject_list)
        self.comboBox_165.addItems(subject_list)
        self.comboBox_166.addItems(subject_list)
        self.comboBox_167.addItems(subject_list)
        self.comboBox_168.addItems(subject_list)
        
        #add teacher name in schedule
        self.comboBox_15.addItems(teacher_list)
        self.comboBox_16.addItems(teacher_list)
        self.comboBox_17.addItems(teacher_list)
        self.comboBox_18.addItems(teacher_list)
        self.comboBox_19.addItems(teacher_list)
        self.comboBox_20.addItems(teacher_list)
        self.comboBox_21.addItems(teacher_list)
        self.comboBox_29.addItems(teacher_list)
        self.comboBox_30.addItems(teacher_list)
        self.comboBox_31.addItems(teacher_list)
        self.comboBox_32.addItems(teacher_list)
        self.comboBox_33.addItems(teacher_list)
        self.comboBox_34.addItems(teacher_list)
        self.comboBox_35.addItems(teacher_list)
        self.comboBox_43.addItems(teacher_list)
        self.comboBox_44.addItems(teacher_list)
        self.comboBox_45.addItems(teacher_list)
        self.comboBox_46.addItems(teacher_list)
        self.comboBox_47.addItems(teacher_list)
        self.comboBox_48.addItems(teacher_list)
        self.comboBox_49.addItems(teacher_list)
        self.comboBox_57.addItems(teacher_list)
        self.comboBox_58.addItems(teacher_list)
        self.comboBox_59.addItems(teacher_list)
        self.comboBox_60.addItems(teacher_list)
        self.comboBox_61.addItems(teacher_list)
        self.comboBox_62.addItems(teacher_list)
        self.comboBox_63.addItems(teacher_list)
        self.comboBox_71.addItems(teacher_list)
        self.comboBox_72.addItems(teacher_list)
        self.comboBox_73.addItems(teacher_list)
        self.comboBox_74.addItems(teacher_list)
        self.comboBox_75.addItems(teacher_list)
        self.comboBox_76.addItems(teacher_list)
        self.comboBox_77.addItems(teacher_list)
        self.comboBox_85.addItems(teacher_list)
        self.comboBox_86.addItems(teacher_list)
        self.comboBox_87.addItems(teacher_list)
        self.comboBox_88.addItems(teacher_list)
        self.comboBox_89.addItems(teacher_list)
        self.comboBox_90.addItems(teacher_list)
        self.comboBox_91.addItems(teacher_list)
        self.comboBox_99.addItems(teacher_list)
        self.comboBox_100.addItems(teacher_list)
        self.comboBox_101.addItems(teacher_list)
        self.comboBox_102.addItems(teacher_list)
        self.comboBox_103.addItems(teacher_list)
        self.comboBox_104.addItems(teacher_list)
        self.comboBox_105.addItems(teacher_list)
        self.comboBox_113.addItems(teacher_list)
        self.comboBox_114.addItems(teacher_list)
        self.comboBox_115.addItems(teacher_list)
        self.comboBox_116.addItems(teacher_list)
        self.comboBox_117.addItems(teacher_list)
        self.comboBox_118.addItems(teacher_list)
        self.comboBox_119.addItems(teacher_list)
        self.comboBox_127.addItems(teacher_list)
        self.comboBox_128.addItems(teacher_list)
        self.comboBox_129.addItems(teacher_list)
        self.comboBox_130.addItems(teacher_list)
        self.comboBox_131.addItems(teacher_list)
        self.comboBox_132.addItems(teacher_list)
        self.comboBox_133.addItems(teacher_list)
        self.comboBox_141.addItems(teacher_list)
        self.comboBox_142.addItems(teacher_list)
        self.comboBox_143.addItems(teacher_list)
        self.comboBox_144.addItems(teacher_list)
        self.comboBox_145.addItems(teacher_list)
        self.comboBox_146.addItems(teacher_list)
        self.comboBox_147.addItems(teacher_list)
        self.comboBox_155.addItems(teacher_list)
        self.comboBox_156.addItems(teacher_list)
        self.comboBox_157.addItems(teacher_list)
        self.comboBox_158.addItems(teacher_list)
        self.comboBox_159.addItems(teacher_list)
        self.comboBox_160.addItems(teacher_list)
        self.comboBox_161.addItems(teacher_list)
        self.comboBox_169.addItems(teacher_list)
        self.comboBox_170.addItems(teacher_list)
        self.comboBox_171.addItems(teacher_list)
        self.comboBox_172.addItems(teacher_list)
        self.comboBox_173.addItems(teacher_list)
        self.comboBox_174.addItems(teacher_list)
        self.comboBox_175.addItems(teacher_list)


        self.comboBox_176.addItems(subject_list)

    def Show_Themes(self):
        self.groupBox.show()

    def Hide_Themes(self):
        self.groupBox.hide()

    def Open_Hod(self):
        if self.logged_in:
            self.tabWidget.setCurrentIndex(4)
        else:
            self.tabWidget.setCurrentIndex(0)

    def Open_Teacher_Schedule(self):
        self.tabWidget.setCurrentIndex(1)

    def Open_Class_Schedule(self):
        self.tabWidget.setCurrentIndex(2)

    def Open_Free_Teacher(self):
        self.tabWidget.setCurrentIndex(3)

    def open_pass_change(self):
        self.tabWidget.setCurrentIndex(5)
        
    def login(self):
        self.label_14.clear()
        self.label_15.clear()
        username=self.lineEdit_3.text()
        password=self.lineEdit_4.text()
        status=login_db(username,password)
        if status==0:
            self.label_14.setText("Username does not exist")
        elif status==2:
            self.label_15.setText("Password incorrect")
        else:
            self.logged_in=True
            self.logged_in_user=username
            self.logged_in_password=password
            self.tabWidget.setCurrentIndex(4)
            self.pushButton_4.hide()
            self.show_logout()
            self.pushButton_14.setText(username)

    def show_logout(self):
        self.widget.show()

    def hide_logout(self):
        self.widget.hide()

    def logout(self):
        self.logged_in=False
        self.hide_logout()
        self.pushButton_4.show()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.tabWidget.setCurrentIndex(0)
        self.logged_in_user=None
        self.logged_in_password=None


    def add_admin(self):
        self.label_16.clear()
        self.label_17.clear()
        self.label_18.clear()
        username = self.lineEdit_5.text()
        password = self.lineEdit_6.text()
        if username=='':
            self.label_16.setText("Cannot be empty")
        elif password=='':
            self.label_17.setText("Cannot be empty")
        elif username==password:
            self.label_16.setText("Cannot be same")
            self.label_17.setText("Cannot be same")
        else:
            x = add_admin_db(username,password)
            if x:
                self.label_18.setText("Added")
                self.handle_drop()
            else:
                self.label_16.setText("Username already exist")
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()

    def remove_admin(self):
        username = self.comboBox_4.currentText()
        remove_admin_db(username)
        self.handle_drop()

    def pass_change(self):
        password1 = self.lineEdit_7.text()
        password2 = self.lineEdit_8.text()
        if password1==password2:
            if password1==self.logged_in_password:
                self.label_21.setText("Same password as before")
            elif password1==self.logged_in_user:
                self.label_21.setText("Password not equal to username")
            else:
                pass_change_db(password1,self.logged_in_user)
                self.label_21.setText("Changed successfully")
        else:
            self.label_21.setText("Passwords do not match")
        self.lineEdit_7.clear()
        self.lineEdit_8.clear() 

    def add_teacher(self):
        Tid=self.lineEdit_9.text()
        Tname=self.lineEdit_10.text()
        Desig=self.comboBox_5.currentText()
        Dept=self.comboBox_6.currentText()
        x=add_teacher_db(Tid,Tname,Desig,Dept)
        if not Tid.isdigit():
            return
        if x==0:
            self.label_28.setText("Id already exist")
        elif x==2:
            self.label_29.setText("Name already exist")
        else:
            self.label_30.setText("Added successfully")
            self.handle_drop()

    def remove_teacher(self):
        teacher = self.comboBox_7.currentText()
        teacher = teacher.split()
        Tid = int(teacher[0])
        remove_teacher_db(Tid)
        self.handle_drop()

    def add_subject(self):
        self.label_41.clear()
        Sid=self.lineEdit_12.text()
        Sname=self.lineEdit_13.text()
        if Sid=='' or Sname=="":
            self.label_41.setText("Field cannot be empty")
            return
        x=add_subject_db(Sid,Sname)
        if x==0:
            self.label_41.setText("Id already exists")
        elif x==2:
            self.label_41.setText("Subject name already exists")
        else:
            self.label_41.setText("Added successfully")
            self.handle_drop()
    
    def remove_subject(self):
        x=self.comboBox_176.currentText()
        x=x.split("    ")
        remove_subject_db(x[0])
        self.handle_drop()

    def add_time_tabe(self):
        l=[]
        l.append(self.lineEdit_11.text())
        l.append(self.comboBox_8.currentText().split()[0])
        l.append(self.comboBox_9.currentText().split()[0])
        l.append(self.comboBox_10.currentText().split()[0])
        l.append(self.comboBox_11.currentText().split()[0])
        l.append(self.comboBox_12.currentText().split()[0])
        l.append(self.comboBox_13.currentText().split()[0])
        l.append(self.comboBox_14.currentText().split()[0])
        l.append(self.comboBox_15.currentText().split()[0])
        l.append(self.comboBox_16.currentText().split()[0])
        l.append(self.comboBox_17.currentText().split()[0])
        l.append(self.comboBox_18.currentText().split()[0])
        l.append(self.comboBox_19.currentText().split()[0])
        l.append(self.comboBox_20.currentText().split()[0])
        l.append(self.comboBox_21.currentText().split()[0])
        l.append(self.comboBox_22.currentText().split()[0])
        l.append(self.comboBox_23.currentText().split()[0])
        l.append(self.comboBox_24.currentText().split()[0])
        l.append(self.comboBox_25.currentText().split()[0])
        l.append(self.comboBox_26.currentText().split()[0])
        l.append(self.comboBox_27.currentText().split()[0])
        l.append(self.comboBox_28.currentText().split()[0])
        l.append(self.comboBox_29.currentText().split()[0])
        l.append(self.comboBox_30.currentText().split()[0])
        l.append(self.comboBox_31.currentText().split()[0])
        l.append(self.comboBox_32.currentText().split()[0])
        l.append(self.comboBox_33.currentText().split()[0])
        l.append(self.comboBox_34.currentText().split()[0])
        l.append(self.comboBox_35.currentText().split()[0])
        l.append(self.comboBox_36.currentText().split()[0])
        l.append(self.comboBox_37.currentText().split()[0])
        l.append(self.comboBox_38.currentText().split()[0])
        l.append(self.comboBox_39.currentText().split()[0])
        l.append(self.comboBox_40.currentText().split()[0])
        l.append(self.comboBox_41.currentText().split()[0])
        l.append(self.comboBox_42.currentText().split()[0])
        l.append(self.comboBox_43.currentText().split()[0])
        l.append(self.comboBox_44.currentText().split()[0])
        l.append(self.comboBox_45.currentText().split()[0])
        l.append(self.comboBox_46.currentText().split()[0])
        l.append(self.comboBox_47.currentText().split()[0])
        l.append(self.comboBox_48.currentText().split()[0])
        l.append(self.comboBox_49.currentText().split()[0])
        l.append(self.comboBox_50.currentText().split()[0])
        l.append(self.comboBox_51.currentText().split()[0])
        l.append(self.comboBox_52.currentText().split()[0])
        l.append(self.comboBox_53.currentText().split()[0])
        l.append(self.comboBox_54.currentText().split()[0])
        l.append(self.comboBox_55.currentText().split()[0])
        l.append(self.comboBox_56.currentText().split()[0])
        l.append(self.comboBox_57.currentText().split()[0])
        l.append(self.comboBox_58.currentText().split()[0])
        l.append(self.comboBox_59.currentText().split()[0])
        l.append(self.comboBox_60.currentText().split()[0])
        l.append(self.comboBox_61.currentText().split()[0])
        l.append(self.comboBox_62.currentText().split()[0])
        l.append(self.comboBox_63.currentText().split()[0])
        l.append(self.comboBox_64.currentText().split()[0])
        l.append(self.comboBox_65.currentText().split()[0])
        l.append(self.comboBox_66.currentText().split()[0])
        l.append(self.comboBox_67.currentText().split()[0])
        l.append(self.comboBox_68.currentText().split()[0])
        l.append(self.comboBox_69.currentText().split()[0])
        l.append(self.comboBox_70.currentText().split()[0])
        l.append(self.comboBox_71.currentText().split()[0])
        l.append(self.comboBox_72.currentText().split()[0])
        l.append(self.comboBox_73.currentText().split()[0])
        l.append(self.comboBox_74.currentText().split()[0])
        l.append(self.comboBox_75.currentText().split()[0])
        l.append(self.comboBox_76.currentText().split()[0])
        l.append(self.comboBox_77.currentText().split()[0])
        l.append(self.comboBox_78.currentText().split()[0])
        l.append(self.comboBox_79.currentText().split()[0])
        l.append(self.comboBox_80.currentText().split()[0])
        l.append(self.comboBox_81.currentText().split()[0])
        l.append(self.comboBox_82.currentText().split()[0])
        l.append(self.comboBox_83.currentText().split()[0])
        l.append(self.comboBox_84.currentText().split()[0])
        l.append(self.comboBox_85.currentText().split()[0])
        l.append(self.comboBox_86.currentText().split()[0])
        l.append(self.comboBox_87.currentText().split()[0])
        l.append(self.comboBox_88.currentText().split()[0])
        l.append(self.comboBox_89.currentText().split()[0])
        l.append(self.comboBox_90.currentText().split()[0])
        l.append(self.comboBox_91.currentText().split()[0])
        l.append(self.comboBox_92.currentText().split()[0])
        l.append(self.comboBox_93.currentText().split()[0])
        l.append(self.comboBox_94.currentText().split()[0])
        l.append(self.comboBox_95.currentText().split()[0])
        l.append(self.comboBox_96.currentText().split()[0])
        l.append(self.comboBox_97.currentText().split()[0])
        l.append(self.comboBox_98.currentText().split()[0])
        l.append(self.comboBox_99.currentText().split()[0])
        l.append(self.comboBox_100.currentText().split()[0])
        l.append(self.comboBox_101.currentText().split()[0])
        l.append(self.comboBox_102.currentText().split()[0])
        l.append(self.comboBox_103.currentText().split()[0])
        l.append(self.comboBox_104.currentText().split()[0])
        l.append(self.comboBox_105.currentText().split()[0])
        l.append(self.comboBox_106.currentText().split()[0])
        l.append(self.comboBox_107.currentText().split()[0])
        l.append(self.comboBox_108.currentText().split()[0])
        l.append(self.comboBox_109.currentText().split()[0])
        l.append(self.comboBox_110.currentText().split()[0])
        l.append(self.comboBox_111.currentText().split()[0])
        l.append(self.comboBox_112.currentText().split()[0])
        l.append(self.comboBox_113.currentText().split()[0])
        l.append(self.comboBox_114.currentText().split()[0])
        l.append(self.comboBox_115.currentText().split()[0])
        l.append(self.comboBox_116.currentText().split()[0])
        l.append(self.comboBox_117.currentText().split()[0])
        l.append(self.comboBox_118.currentText().split()[0])
        l.append(self.comboBox_119.currentText().split()[0])
        l.append(self.comboBox_120.currentText().split()[0])
        l.append(self.comboBox_121.currentText().split()[0])
        l.append(self.comboBox_122.currentText().split()[0])
        l.append(self.comboBox_123.currentText().split()[0])
        l.append(self.comboBox_124.currentText().split()[0])
        l.append(self.comboBox_125.currentText().split()[0])
        l.append(self.comboBox_126.currentText().split()[0])
        l.append(self.comboBox_127.currentText().split()[0])
        l.append(self.comboBox_128.currentText().split()[0])
        l.append(self.comboBox_129.currentText().split()[0])
        l.append(self.comboBox_130.currentText().split()[0])
        l.append(self.comboBox_131.currentText().split()[0])
        l.append(self.comboBox_132.currentText().split()[0])
        l.append(self.comboBox_133.currentText().split()[0])
        l.append(self.comboBox_134.currentText().split()[0])
        l.append(self.comboBox_135.currentText().split()[0])
        l.append(self.comboBox_136.currentText().split()[0])
        l.append(self.comboBox_137.currentText().split()[0])
        l.append(self.comboBox_138.currentText().split()[0])
        l.append(self.comboBox_139.currentText().split()[0])
        l.append(self.comboBox_140.currentText().split()[0])
        l.append(self.comboBox_141.currentText().split()[0])
        l.append(self.comboBox_142.currentText().split()[0])
        l.append(self.comboBox_143.currentText().split()[0])
        l.append(self.comboBox_144.currentText().split()[0])
        l.append(self.comboBox_145.currentText().split()[0])
        l.append(self.comboBox_146.currentText().split()[0])
        l.append(self.comboBox_147.currentText().split()[0])
        l.append(self.comboBox_148.currentText().split()[0])
        l.append(self.comboBox_149.currentText().split()[0])
        l.append(self.comboBox_150.currentText().split()[0])
        l.append(self.comboBox_151.currentText().split()[0])
        l.append(self.comboBox_152.currentText().split()[0])
        l.append(self.comboBox_153.currentText().split()[0])
        l.append(self.comboBox_154.currentText().split()[0])
        l.append(self.comboBox_155.currentText().split()[0])
        l.append(self.comboBox_156.currentText().split()[0])
        l.append(self.comboBox_157.currentText().split()[0])
        l.append(self.comboBox_158.currentText().split()[0])
        l.append(self.comboBox_159.currentText().split()[0])
        l.append(self.comboBox_160.currentText().split()[0])
        l.append(self.comboBox_161.currentText().split()[0])
        l.append(self.comboBox_162.currentText().split()[0])
        l.append(self.comboBox_163.currentText().split()[0])
        l.append(self.comboBox_164.currentText().split()[0])
        l.append(self.comboBox_165.currentText().split()[0])
        l.append(self.comboBox_166.currentText().split()[0])
        l.append(self.comboBox_167.currentText().split()[0])
        l.append(self.comboBox_168.currentText().split()[0])
        l.append(self.comboBox_169.currentText().split()[0])
        l.append(self.comboBox_170.currentText().split()[0])
        l.append(self.comboBox_171.currentText().split()[0])
        l.append(self.comboBox_172.currentText().split()[0])
        l.append(self.comboBox_173.currentText().split()[0])
        l.append(self.comboBox_174.currentText().split()[0])
        l.append(self.comboBox_175.currentText().split()[0])
        add_time_tabe_db(l)

def main():
    app=QApplication(sys.argv)
    window=MainApp()
    window.show()
    app.exec_()

if __name__=='__main__':
    main()